### ISSUE TITLE
process_enumeration 1467: ASSERT FAILED

### ISSUE THREAD

**Issue by smeredith** [rppicomidi/ble-midi2usbhost#1]
BLE seems to be working, but when connect the USB (via an OTG cable) I get a failed assertion message and it doesn't work.

Here is the debug output: 

Pico W BLE-MIDI to USB Host Adapter
Version: 7.95.61 (abcd531 CY) CRC: 4528a809 Date: Wed 2023-01-11 10:29:38 PST Ucode Ver: 1043.2169 FWID 01-7afb0879
cyw43 loaded ok, mac 28:cd:c1:0c:24:b4
BT FW download, version = CYW4343A2_001.003.016.0031.0000_Generic_SDIO_37MHz_wlbga_BU_dl_signed
BTstack up and running on 28:CD:C1:0C:24:B5.
process_enumeration 1467: ASSERT FAILED

I pulled the latest Pico SDK, then pulled master of tinyusb per your instructions.

**Comment by smeredith** [comment]
This is what you see if you need to increase CFG_TUH_ENUMERATION_BUFSIZE in tusb_config.h. Increasing this solved the problem.

**Comment by rppicomidi** [comment]
@smeredith Just so I understand, you had an issue enumerating the MIDI device, but increasing `CFG_TUH_ENUMERATION_BUFSIZE` solved your issue? If that is true, please tell me what MIDI device caused the issue. Last week I helped someone else debug an issue with guitar pedals. The MIDI interface itself was small, but the audio descriptor was much larger and exceeded the 256 byte default. I am thinking of going through my projects and bumping up `CFG_TUH_ENUMERATION_BUFSIZE` on all of them.

**Comment by smeredith** [comment]
Yes, it is as you describe. The MIDI device is a Korg Liano (a keyboard). The new value I used is 1024.

If this assertion is in your library code, is a better diagnostic message possible?

**Comment by rppicomidi** [comment]
@smeredith The assert happens in the TinyUSB library before it ever tries to call any code in the usb_midi_host library, so I don't have any control over it.

If I may ask, how did you arrive at `CFG_TUH_ENUMERATION_BUFSIZE` of 1024? Did you dump the descriptor of your Korg Liano? I was going to go for a 512 byte buffer, but if you saw a descriptor over 512 bytes long, then maybe I will use 1024 bytes instead when I update my projects.

**Comment by smeredith** [comment]
I selected 1024 at random.

**Comment by rppicomidi** [comment]
@smeredith I just pushed an update to this code that increased `CFG_TUH_ENUMERATION_BUFSIZE` to 512 and added a troubleshooting section to the `README.md` file. If you have time to try the updated code, please let me know if the 512 byte buffer worked for you. If it did, please close this bug. If it didn't, I would greatly appreciate it if you would dump your keyboard's USB descriptor (as described in the `README.md` troubleshooting section) and attach the descriptor dump to this issue.
Thank you for your help.

**Comment by smeredith** [comment]
512 is sufficient for my instrument.
